# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ab9/projects/sa-ptv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ab9/projects/sa-ptv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ab9/projects/sa-ptv/CMakeFiles /home/ab9/projects/sa-ptv/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ab9/projects/sa-ptv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sa-ptv

# Build rule for target.
sa-ptv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sa-ptv
.PHONY : sa-ptv

# fast build rule for target.
sa-ptv/fast:
	$(MAKE) -f CMakeFiles/sa-ptv.dir/build.make CMakeFiles/sa-ptv.dir/build
.PHONY : sa-ptv/fast

#=============================================================================
# Target rules for targets named lib

# Build rule for target.
lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib
.PHONY : lib

# fast build rule for target.
lib/fast:
	$(MAKE) -f lib/CMakeFiles/lib.dir/build.make lib/CMakeFiles/lib.dir/build
.PHONY : lib/fast

sa-ptv.o: sa-ptv.cpp.o
.PHONY : sa-ptv.o

# target to build an object file
sa-ptv.cpp.o:
	$(MAKE) -f CMakeFiles/sa-ptv.dir/build.make CMakeFiles/sa-ptv.dir/sa-ptv.cpp.o
.PHONY : sa-ptv.cpp.o

sa-ptv.i: sa-ptv.cpp.i
.PHONY : sa-ptv.i

# target to preprocess a source file
sa-ptv.cpp.i:
	$(MAKE) -f CMakeFiles/sa-ptv.dir/build.make CMakeFiles/sa-ptv.dir/sa-ptv.cpp.i
.PHONY : sa-ptv.cpp.i

sa-ptv.s: sa-ptv.cpp.s
.PHONY : sa-ptv.s

# target to generate assembly for a file
sa-ptv.cpp.s:
	$(MAKE) -f CMakeFiles/sa-ptv.dir/build.make CMakeFiles/sa-ptv.dir/sa-ptv.cpp.s
.PHONY : sa-ptv.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sa-ptv"
	@echo "... lib"
	@echo "... sa-ptv.o"
	@echo "... sa-ptv.i"
	@echo "... sa-ptv.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

