#!/bin/bash

# build non CUDA image
cd base-no-cuda
docker build -t openfv-base-notebook .
cd ../minimal-notebook
docker build -t openfv-minimal-notebook .
cd ../scipy-notebook
docker build -t openfv-scipy-notebook .
cd ..
docker build -t openfv .

# remove intermediate images
docker rmi -f openfv-base-notebook openfv-minimal-notebook openfv-scipy-notebook

# build CUDA image
cd base-notebook
docker build -t openfv-base-notebook .
cd ../minimal-notebook
docker build -t openfv-minimal-notebook .
cd ../scipy-notebook
docker build -t openfv-scipy-notebook .
cd ../cuda
docker build -t openfv-cuda .

docker rmi -f openfv-base-notebook openfv-minimal-notebook openfv-scipy-notebook
