#!/bin/bash

# Checking out and unstaging required files from master
git checkout master source
git checkout master config
git checkout master Makefile
git rm -r --cached source
git rm --cached config
git rm --cached Makefile

# Building docs
make html

# Cleaning up
rm config
rm Makefile
